name: Publish to WinGet

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to release (e.g. app-v0.7.0)"
        required: true
        default: "app-v0.7.0"

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: jousse.pomodorolm
          installers-regex: '\.msi$'
          token: ${{ secrets.WINGET_TOKEN }}
          # If run manually, use the input. If run automatically, use the release tag.
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
